
You can support this project in many different ways, such as sending your pull request, or by donating BTC, or whether you prefer you may directly contact me.

Bitcoin Deposit Address: 3KZWbLR8td2mG2dWFyVbmPe9ZYBcbfERFQ
